name: tasia

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  tasia:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /tasia') ||
      startsWith(github.event.comment.body, '/tasia')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run tasia
        uses: anomalyco/tasia/github@latest
        env:
          TASIA_API_KEY: ${{ secrets.TASIA_API_KEY }}
          TASIA_PERMISSION: '{"bash": "deny"}'
        with:
          model: tasia/claude-opus-4-5
